cloud:
  aws:
    s3:
      bucket: carrot-market-yechan
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
spring:
  config:
    import :
      - aws.yml
      - localDB.yml
      - jwt.yml
  redis:
    host : 127.0.0.1
    port : 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size : 100
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled : true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
server:
  session:
    tracking-modes: cookie