#cloud:
#  aws:
#    s3:
#      bucket: carrot-market-yechan
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false
#    credentials:
#      instanceProfile: true
spring:
  thymeleaf:
    cache : false
  config:
    import :
#      - aws.yml
      - localDB.yml
      - jwt.yml
  redis:
    host : 127.0.0.1
    port : 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size : 100
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled : true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
server:
  session:
    tracking-modes: cookie

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan:  clone.carrotMarket.api
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: api-docs.html            # Swagger UI 경로 => localhost:8080/api-docs.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true