cloud:
  aws:
    s3:
      bucket: carrot-market-yechan
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
spring:
  datasource:
    url: jdbc:mysql://carrot-market.c9k2rbljcjg7.ap-northeast-2.rds.amazonaws.com:3306/carrotmarket?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: yechankim
    password: yechan123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import : aws.yml
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      default_batch_fetch_size : 100
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled : true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
server:
  session:
    tracking-modes: cookie